// Conceptually-close word pairs for The Ghost
// Each pair: [civilianWord, undercoverWord] - similar but distinct
// The two words should be close enough that descriptions overlap,
// but different enough that careful listening reveals the impostor.

const WORD_PAIRS_EN = [
  // Drinks
  ["Coffee", "Energy Drink"],
  ["Beer", "Vodka"],
  ["Whiskey", "Rum"],
  ["Vodka", "Gin"],
  ["Champagne", "Beer"],
  ["Lemonade", "Iced Tea"],
  ["Coca-Cola", "Pepsi"],
  ["Espresso", "Cappuccino"],
  ["Milk", "Water"],
  ["Juice", "Wine"],

  // Food - savory
  ["Pizza", "Burger"],
  ["Burger", "Taco"],
  ["Hot Dog", "Kebab"],
  ["Pasta", "Rice"],
  ["Sushi", "Poke Bowl"],
  ["Taco", "Sandwich"],
  ["Steak", "Roast"],
  ["Soup", "Stew"],
  ["Salad", "Coleslaw"],
  ["Bread", "Bagel"],
  ["Bacon", "Ham"],
  ["Chicken", "Turkey"],
  ["Lobster", "Crab"],
  ["Salmon", "Tuna"],
  ["Curry", "Stir-fry"],
  ["Risotto", "Paella"],
  ["Crepe", "Waffle"],
  ["Fries", "Mashed Potatoes"],
  ["Pretzel", "Popcorn"],
  ["Lasagna", "Moussaka"],

  // Food - sweet
  ["Chocolate", "Caramel"],
  ["Cake", "Donut"],
  ["Cookie", "Chocolate Bar"],
  ["Ice Cream", "Sorbet"],
  ["Donut", "Bagel"],
  ["Pie", "Tart"],
  ["Brownie", "Blondie"],
  ["Pudding", "Yogurt"],
  ["Macaron", "Cookie"],
  ["Waffle", "Pancake"],

  // Fruit
  ["Apple", "Pear"],
  ["Orange", "Banana"],
  ["Lemon", "Grapefruit"],
  ["Strawberry", "Raspberry"],
  ["Blueberry", "Blackberry"],
  ["Grape", "Cherry"],
  ["Banana", "Apple"],
  ["Watermelon", "Pineapple"],
  ["Peach", "Apricot"],
  ["Pineapple", "Mango"],
  ["Coconut", "Avocado"],
  ["Fig", "Date"],

  // Animals - mammals
  ["Dog", "Bear"],
  ["Cat", "Lion"],
  ["Tiger", "Zebra"],
  ["Lion", "Gorilla"],
  ["Horse", "Donkey"],
  ["Cow", "Horse"],
  ["Sheep", "Goat"],
  ["Pig", "Boar"],
  ["Rabbit", "Squirrel"],
  ["Mouse", "Rat"],
  ["Squirrel", "Chipmunk"],
  ["Elephant", "Rhino"],
  ["Giraffe", "Camel"],
  ["Bear", "Panda"],
  ["Monkey", "Chimpanzee"],
  ["Dolphin", "Penguin"],
  ["Seal", "Octopus"],
  ["Hamster", "Guinea Pig"],
  ["Fox", "Coyote"],
  ["Hedgehog", "Mouse"],

  // Animals - birds
  ["Eagle", "Hawk"],
  ["Owl", "Falcon"],
  ["Duck", "Swan"],
  ["Parrot", "Crow"],
  ["Penguin", "Puffin"],
  ["Crow", "Eagle"],
  ["Pigeon", "Bat"],
  ["Chicken", "Pheasant"],
  ["Flamingo", "Crane"],
  ["Sparrow", "Robin"],

  // Animals - others
  ["Snake", "Eel"],
  ["Turtle", "Snail"],
  ["Crocodile", "Shark"],
  ["Frog", "Lizard"],
  ["Shark", "Barracuda"],
  ["Octopus", "Squid"],
  ["Bee", "Wasp"],
  ["Butterfly", "Hummingbird"],
  ["Spider", "Scorpion"],
  ["Ant", "Termite"],

  // Sports
  ["Football", "Rugby"],
  ["Soccer", "Tennis"],
  ["Basketball", "Baseball"],
  ["Tennis", "Badminton"],
  ["Baseball", "Cricket"],
  ["Hockey", "Lacrosse"],
  ["Golf", "Mini Golf"],
  ["Swimming", "Diving"],
  ["Boxing", "Wrestling"],
  ["Karate", "Taekwondo"],
  ["Skiing", "Snowboarding"],
  ["Surfing", "Skateboarding"],
  ["Cycling", "Motorcycling"],
  ["Marathon", "Triathlon"],
  ["Bowling", "Curling"],
  ["Archery", "Darts"],
  ["Yoga", "Pilates"],

  // Music & instruments
  ["Guitar", "Violin"],
  ["Piano", "Organ"],
  ["Violin", "Flute"],
  ["Drums", "Bongos"],
  ["Flute", "Clarinet"],
  ["Trumpet", "Trombone"],
  ["Saxophone", "Trumpet"],
  ["Harmonica", "Accordion"],
  ["Microphone", "Megaphone"],
  ["Headphones", "Earbuds"],

  // Vehicles
  ["Car", "Truck"],
  ["Bicycle", "Scooter"],
  ["Motorcycle", "Moped"],
  ["Plane", "Helicopter"],
  ["Boat", "Yacht"],
  ["Train", "Subway"],
  ["Bus", "Tram"],
  ["Submarine", "Ship"],
  ["Spaceship", "Rocket"],
  ["Skateboard", "Roller Skates"],
  ["Taxi", "Uber"],
  ["Ambulance", "Fire Truck"],
  ["Tank", "Bulldozer"],

  // Places
  ["Beach", "Lake"],
  ["Mountain", "Hill"],
  ["Forest", "Jungle"],
  ["Desert", "Savanna"],
  ["River", "Stream"],
  ["Ocean", "Sea"],
  ["City", "Town"],
  ["Village", "Suburb"],
  ["Farm", "Ranch"],
  ["Castle", "Palace"],
  ["Library", "Bookstore"],
  ["Museum", "Gallery"],
  ["Hospital", "Clinic"],
  ["School", "University"],
  ["Restaurant", "Cafe"],
  ["Hotel", "Motel"],
  ["Cinema", "Theatre"],
  ["Park", "Garden"],
  ["Stadium", "Arena"],
  ["Airport", "Train Station"],
  ["Bank", "Casino"],
  ["Church", "Cathedral"],
  ["Mosque", "Museum"],
  ["Bar", "Pub"],
  ["Nightclub", "Library"],

  // Famous places
  ["Paris", "London"],
  ["Tokyo", "Seoul"],
  ["New York", "Los Angeles"],
  ["Rome", "Athens"],
  ["Egypt", "Greece"],
  ["China", "Japan"],
  ["Spain", "Italy"],
  ["Germany", "Austria"],
  ["Brazil", "Argentina"],
  ["Canada", "Australia"],
  ["Eiffel Tower", "Big Ben"],
  ["Statue of Liberty", "Mount Rushmore"],
  ["Pyramid", "Sphinx"],

  // Professions
  ["Doctor", "Scientist"],
  ["Teacher", "Coach"],
  ["Police", "Soldier"],
  ["Firefighter", "Paramedic"],
  ["Chef", "Baker"],
  ["Lawyer", "Politician"],
  ["Pilot", "Flight Attendant"],
  ["Soldier", "Sailor"],
  ["Scientist", "Engineer"],
  ["Artist", "Sculptor"],
  ["Writer", "Journalist"],
  ["Actor", "Comedian"],
  ["Singer", "Rapper"],
  ["Dancer", "Choreographer"],
  ["Photographer", "Filmmaker"],
  ["Architect", "Designer"],
  ["Plumber", "Electrician"],
  ["Carpenter", "Mason"],
  ["Farmer", "Gardener"],
  ["Mechanic", "Technician"],
  ["Programmer", "Hacker"],
  ["Astronaut", "Explorer"],
  ["Magician", "Hypnotist"],
  ["Boxer", "Wrestler"],
  ["Spy", "Assassin"],

  // Body parts
  ["Hand", "Foot"],
  ["Eye", "Ear"],
  ["Nose", "Mouth"],
  ["Arm", "Leg"],
  ["Finger", "Toe"],
  ["Heart", "Lung"],
  ["Brain", "Spine"],
  ["Tooth", "Bone"],
  ["Hair", "Beard"],

  // Household objects
  ["Chair", "Stool"],
  ["Sofa", "Bench"],
  ["Bed", "Hammock"],
  ["Pillow", "Cloud"],
  ["Table", "Desk"],
  ["Lamp", "Candle"],
  ["Window", "Door"],
  ["Carpet", "Grass"],
  ["Mirror", "Picture"],
  ["Clock", "Watch"],
  ["Knife", "Sword"],
  ["Plate", "Bowl"],
  ["Cup", "Mug"],
  ["Bottle", "Jar"],
  ["Spoon", "Ladle"],
  ["Pan", "Pot"],
  ["Oven", "Microwave"],
  ["Fridge", "Freezer"],
  ["Sink", "Bathtub"],
  ["Shower", "Bath"],
  ["Toilet", "Sink"],
  ["Vacuum", "Lawnmower"],
  ["Washing Machine", "Dishwasher"],
  ["Television", "Cinema"],
  ["Radio", "Speaker"],
  ["Phone", "Tablet"],
  ["Laptop", "Smartphone"],
  ["Camera", "Binoculars"],
  ["Pen", "Pencil"],
  ["Book", "Magazine"],
  ["Newspaper", "Pamphlet"],

  // Clothing
  ["Shirt", "Blouse"],
  ["Pants", "Shorts"],
  ["Dress", "Skirt"],
  ["Jacket", "Coat"],
  ["Sweater", "Hoodie"],
  ["Hat", "Cap"],
  ["Hat", "Helmet"],
  ["Socks", "Stockings"],
  ["Shoes", "Boots"],
  ["Sneakers", "Sandals"],
  ["Tie", "Bow Tie"],
  ["Belt", "Rope"],
  ["Scarf", "Shawl"],
  ["Sunglasses", "Goggles"],
  ["Suit", "Tuxedo"],
  ["Pajamas", "Robe"],
  ["Bikini", "Swimsuit"],

  // Weather & nature
  ["Rain", "Snow"],
  ["Rain", "Waterfall"],
  ["Sun", "Fire"],
  ["Cloud", "Fog"],
  ["Wind", "Breeze"],
  ["Thunder", "Lightning"],
  ["Rainbow", "Aurora"],
  ["Tree", "Bush"],
  ["Flower", "Plant"],
  ["Rose", "Tulip"],
  ["Grass", "Moss"],
  ["Cactus", "Bamboo"],
  ["Mushroom", "Truffle"],

  // Movies / pop culture (general)
  ["Superhero", "Villain"],
  ["Vampire", "Werewolf"],
  ["Zombie", "Ghost"],
  ["Wizard", "Witch"],
  ["Dragon", "Phoenix"],
  ["Knight", "Samurai"],
  ["Pirate", "Sailor"],
  ["Cowboy", "Knight"],
  ["Ninja", "Samurai"],
  ["Robot", "Android"],
  ["Alien", "Monster"],
  ["King", "Emperor"],
  ["Queen", "Princess"],
  ["Prince", "Duke"],

  // Tools & objects
  ["Hammer", "Drill"],
  ["Screwdriver", "Hammer"],
  ["Saw", "Knife"],
  ["Drill", "Jackhammer"],
  ["Nail", "Glue"],
  ["Rope", "String"],
  ["Ladder", "Stairs"],
  ["Bucket", "Barrel"],
  ["Box", "Crate"],
  ["Bag", "Backpack"],
  ["Suitcase", "Briefcase"],
  ["Wallet", "Purse"],
  ["Umbrella", "Parasol"],
  ["Key", "Lock"],
  ["Map", "GPS"],
  ["Telescope", "Microscope"],
  ["Flashlight", "Lantern"],
  ["Sword", "Shield"],
  ["Bow", "Crossbow"],
  ["Gun", "Bow"],
  ["Bomb", "Grenade"],
  ["Shield", "Armor"],

  // Games & entertainment
  ["Chess", "Checkers"],
  ["Cards", "Dice"],
  ["Puzzle", "Crossword"],
  ["Video Game", "Board Game"],
  ["Roller Coaster", "Ferris Wheel"],
  ["Circus", "Carnival"],
  ["Concert", "Festival"],
  ["Movie", "TV Show"],
  ["Comedy", "Drama"],
  ["Horror", "Thriller"],

  // School & office
  ["Backpack", "Briefcase"],
  ["Notebook", "Diary"],
  ["Calculator", "Abacus"],
  ["Eraser", "White-Out"],
  ["Stapler", "Tape"],
  ["Marker", "Highlighter"],
  ["Folder", "Binder"],
  ["Whiteboard", "Chalkboard"],

  // Money & finance
  ["Cash", "Gold"],
  ["Coin", "Bill"],
  ["Gold", "Sun"],
  ["Diamond", "Ruby"],
  ["Treasure", "Loot"],
  ["Bank", "Safe"],
  ["Stock", "Bond"],

  // Abstract / emotions
  ["Love", "Friendship"],
  ["Anger", "Frustration"],
  ["Joy", "Happiness"],
  ["Fear", "Anxiety"],
  ["Dream", "Nightmare"],
  ["Hope", "Faith"],
  ["Truth", "Fact"],
  ["Lie", "Secret"],

  // Time & seasons
  ["Spring", "Autumn"],
  ["Summer", "Winter"],
  ["Morning", "Dawn"],
  ["Day", "Week"],
  ["Christmas", "New Year"],
  ["Halloween", "Easter"],
  ["Birthday", "Anniversary"],
  ["Wedding", "Funeral"],

  // Misc
  ["Gym", "Spa"],
  ["Pool", "Jacuzzi"],
  ["Sauna", "Steam Room"],
  ["Tent", "Cabin"],
  ["Bonfire", "Fireplace"],
  ["BBQ", "Campfire"],
  ["Vacation", "Holiday"],
  ["Road Trip", "Cruise"],
  ["Hiking", "Camping"],
  ["Fishing", "Hunting"],
  ["Painting", "Drawing"],
  ["Photography", "Filmmaking"],
  ["Reading", "Writing"],
  ["Sleeping", "Napping"],
  ["Running", "Jogging"],
  ["Walking", "Marching"],
  ["Crying", "Laughing"],
  ["Whisper", "Shout"],
  ["Hug", "Kiss"],
  ["Handshake", "High Five"],

  // Tech
  ["Internet", "Wi-Fi"],
  ["Email", "Letter"],
  ["Website", "App"],
  ["Bluetooth", "USB"],
  ["Battery", "Plug"],
  ["Charger", "Cable"],
  ["Speaker", "Headphones"],
  ["Keyboard", "Mouse"],
  ["Printer", "Scanner"],
  ["Wallet", "Bank Account"],

  // Mythical / fantasy
  ["Unicorn", "Pegasus"],
  ["Mermaid", "Siren"],
  ["Fairy", "Elf"],
  ["Goblin", "Orc"],
  ["Ghost", "Zombie"],
  ["Angel", "Demon"],
  ["God", "Devil"],

  // Random pairs
  ["Soap", "Shampoo"],
  ["Toothbrush", "Toothpaste"],
  ["Razor", "Comb"],
  ["Perfume", "Cologne"],
  ["Lipstick", "Mascara"],
  ["Necklace", "Bracelet"],
  ["Ring", "Earring"],
  ["Crown", "Tiara"],
  ["Glasses", "Contacts"],
  ["Bandage", "Cast"],
  ["Pill", "Vitamin"],
  ["Candy", "Cake"],
  ["Marshmallow", "Cloud"],
  ["Popcorn", "Chips"],
  ["Nut", "Seed"],
  ["Honey", "Maple Syrup"],
  ["Salt", "Sand"],
  ["Pepper", "Cinnamon"],
  ["Butter", "Margarine"],
  ["Yogurt", "Pudding"],
  ["Cheese", "Butter"],
  ["Egg", "Tofu"],
  ["Rice", "Quinoa"],
  ["Wheat", "Oats"],

  // Advanced
  ["Breeze", "Breath"],
  ["Shadow", "Reflection"],
  ["Silence", "Void"],
  ["Bridge", "Tunnel"],
  ["Passport", "Ticket"],
  ["Battery", "Fuel"],
  ["Signature", "Fingerprint"],
  ["Volcano", "Geyser"],
  ["Statue", "Mannequin"],
  ["Compass", "Anchor"],
  ["Mirror", "Window"],
  ["Cradle", "Coffin"],
  ["Mask", "Makeup"],
  ["Poison", "Medicine"],
];

const WORD_PAIRS_FR = [
  // Boissons
  ["Café", "Boisson énergisante"], ["Bière", "Vodka"], ["Whisky", "Rhum"], ["Vodka", "Gin"],
  ["Champagne", "Bière"], ["Limonade", "Thé glacé"], ["Coca-Cola", "Pepsi"],
  ["Espresso", "Cappuccino"], ["Lait", "Eau"], ["Jus", "Vin"],

  // Nourriture - salé
  ["Pizza", "Burger"], ["Burger", "Tacos"], ["Hot Dog", "Kebab"],
  ["Pâtes", "Riz"], ["Sushi", "Poke Bowl"], ["Tacos", "Sandwich"],
  ["Steak", "Rôti"], ["Soupe", "Ragoût"], ["Salade", "Chou"], ["Pain", "Bagel"],
  ["Bacon", "Jambon"], ["Poulet", "Dinde"], ["Homard", "Crabe"],
  ["Saumon", "Thon"], ["Curry", "Wok"], ["Risotto", "Paella"],
  ["Crêpe", "Gaufre"], ["Frites", "Purée"], ["Bretzel", "Popcorn"],
  ["Lasagnes", "Moussaka"],

  // Nourriture - sucré
  ["Chocolat", "Caramel"], ["Gâteau", "Cupcake"], ["Biscuit", "Cookie"],
  ["Glace", "Sorbet"], ["Donut", "Muffin"], ["Tarte", "Tourte"],
  ["Brownie", "Blondie"], ["Pudding", "Yaourt"], ["Macaron", "Biscuit"],
  ["Gaufre", "Crêpe"],

  // Fruits
  ["Pomme", "Banane"], ["Orange", "Banane"], ["Citron", "Pamplemousse"],
  ["Fraise", "Framboise"], ["Myrtille", "Mûre"], ["Raisin", "Cerise"],
  ["Banane", "Pomme"], ["Pastèque", "Ananas"], ["Pêche", "Abricot"],
  ["Ananas", "Melon"], ["Noix de coco", "Avocat"], ["Figue", "Datte"],

  // Animaux - mammifères
  ["Chien", "Ours"], ["Chat", "Lion"], ["Tigre", "Zèbre"], ["Lion", "Gorille"],
  ["Cheval", "Âne"], ["Vache", "Cheval"], ["Mouton", "Chèvre"],
  ["Cochon", "Sanglier"], ["Lapin", "Écureuil"], ["Souris", "Rat"],
  ["Écureuil", "Rat"], ["Éléphant", "Rhinocéros"], ["Girafe", "Chameau"],
  ["Ours", "Panda"], ["Singe", "Chimpanzé"], ["Dauphin", "Pingouin"],
  ["Phoque", "Pieuvre"], ["Hamster", "Cochon d'Inde"], ["Renard", "Coyote"],
  ["Hérisson", "Souris"],

  // Animaux - oiseaux
  ["Aigle", "Faucon"], ["Hibou", "Chouette"], ["Canard", "Cygne"],
  ["Perroquet", "Corbeau"], ["Pingouin", "Macareux"], ["Corbeau", "Aigle"],
  ["Pigeon", "Chauve-souris"], ["Poulet", "Faisan"], ["Flamant rose", "Grue"],
  ["Moineau", "Rouge-gorge"],

  // Animaux - autres
  ["Serpent", "Anguille"], ["Tortue", "Escargot"], ["Crocodile", "Requin"],
  ["Grenouille", "Lézard"], ["Requin", "Barracuda"], ["Poulpe", "Calmar"],
  ["Abeille", "Guêpe"], ["Papillon", "Mite"], ["Araignée", "Scorpion"],
  ["Fourmi", "Termite"],

  // Sports
  ["Football", "Rugby"], ["Football", "Basketball"], ["Basket", "Volley"],
  ["Tennis", "Badminton"], ["Baseball", "Cricket"], ["Hockey", "Lacrosse"],
  ["Golf", "Mini-golf"], ["Natation", "Plongeon"], ["Boxe", "Lutte"],
  ["Karaté", "Taekwondo"], ["Ski", "Snowboard"], ["Surf", "Skate"],
  ["Vélo", "Moto"], ["Marathon", "Triathlon"], ["Bowling", "Curling"],
  ["Tir à l'arc", "Fléchettes"], ["Yoga", "Pilates"],

  // Musique
  ["Guitare", "Violon"], ["Piano", "Orgue"], ["Violon", "Flûte"],
  ["Batterie", "Bongos"], ["Flûte", "Clarinette"], ["Trompette", "Trombone"],
  ["Saxophone", "Trompette"], ["Harmonica", "Accordéon"],
  ["Microphone", "Mégaphone"], ["Casque", "Écouteurs"],

  // Véhicules
  ["Voiture", "Camion"], ["Vélo", "Trottinette"], ["Moto", "Mobylette"],
  ["Avion", "Hélicoptère"], ["Bateau", "Yacht"], ["Train", "Métro"],
  ["Bus", "Tramway"], ["Sous-marin", "Navire"], ["Fusée", "Navette"],
  ["Skate", "Rollers"], ["Taxi", "Uber"], ["Ambulance", "Pompier"],
  ["Tank", "Bulldozer"],

  // Lieux
  ["Plage", "Lac"], ["Montagne", "Colline"], ["Forêt", "Jungle"],
  ["Désert", "Savane"], ["Rivière", "Ruisseau"], ["Océan", "Mer"],
  ["Ville", "Village"], ["Banlieue", "Village"], ["Ferme", "Ranch"],
  ["Château", "Palais"], ["Bibliothèque", "Librairie"], ["Musée", "Galerie"],
  ["Hôpital", "Clinique"], ["École", "Université"], ["Restaurant", "Café"],
  ["Hôtel", "Motel"], ["Cinéma", "Théâtre"], ["Parc", "Jardin"],
  ["Stade", "Arène"], ["Aéroport", "Gare"], ["Banque", "Distributeur"],
  ["Église", "Cathédrale"], ["Mosquée", "Temple"], ["Bar", "Pub"],
  ["Boîte de nuit", "Bibliothèque"],

  // Lieux célèbres
  ["Paris", "Londres"], ["Tokyo", "Séoul"], ["New York", "Los Angeles"],
  ["Rome", "Athènes"], ["Égypte", "Grèce"], ["Chine", "Japon"],
  ["Espagne", "Italie"], ["Allemagne", "Autriche"], ["Brésil", "Argentine"],
  ["Canada", "Australie"], ["Tour Eiffel", "Big Ben"],
  ["Statue de la Liberté", "Mont Rushmore"], ["Pyramide", "Sphinx"],

  // Professions
  ["Médecin", "Scientifique"], ["Professeur", "Entraîneur"],
  ["Policier", "Soldat"], ["Pompier", "Ambulancier"],
  ["Cuisinier", "Boulanger"], ["Avocat", "Juge"], ["Pilote", "Hôtesse"],
  ["Soldat", "Marin"], ["Scientifique", "Ingénieur"], ["Artiste", "Sculpteur"],
  ["Écrivain", "Journaliste"], ["Acteur", "Comédien"], ["Chanteur", "Rappeur"],
  ["Danseur", "Chorégraphe"], ["Photographe", "Cinéaste"],
  ["Architecte", "Designer"], ["Plombier", "Électricien"],
  ["Charpentier", "Maçon"], ["Fermier", "Jardinier"],
  ["Mécanicien", "Technicien"], ["Programmeur", "Hacker"],
  ["Astronaute", "Explorateur"], ["Magicien", "Hypnotiseur"], ["Boxeur", "Lutteur"],
  ["Espion", "Assassin"],

  // Corps
  ["Main", "Pied"], ["Œil", "Oreille"], ["Nez", "Bouche"], ["Bras", "Jambe"],
  ["Doigt", "Orteil"], ["Cœur", "Poumon"], ["Cerveau", "Colonne"],
  ["Dent", "Os"], ["Cheveux", "Barbe"],

  // Objets maison
  ["Chaise", "Tabouret"], ["Canapé", "Banc"], ["Lit", "Hamac"],
  ["Oreiller", "Coussin"], ["Table", "Bureau"], ["Lampe", "Bougie"],
  ["Fenêtre", "Porte"], ["Tapis", "Carpette"], ["Miroir", "Tableau"],
  ["Horloge", "Montre"], ["Couteau", "Fourchette"], ["Assiette", "Bol"],
  ["Verre", "Tasse"], ["Bouteille", "Bocal"], ["Cuillère", "Louche"],
  ["Poêle", "Casserole"], ["Four", "Micro-ondes"], ["Frigo", "Congélateur"],
  ["Évier", "Baignoire"], ["Douche", "Bain"], ["Toilettes", "Urinoir"],
  ["Aspirateur", "Balai"], ["Lave-linge", "Lave-vaisselle"],
  ["Télévision", "Moniteur"], ["Radio", "Enceinte"], ["Téléphone", "Tablette"],
  ["Portable", "Ordinateur"], ["Caméra", "Jumelles"], ["Stylo", "Crayon"],
  ["Livre", "Magazine"], ["Journal", "Brochure"],

  // Vêtements
  ["Chemise", "Chemisier"], ["Pantalon", "Short"], ["Robe", "Jupe"],
  ["Veste", "Manteau"], ["Pull", "Sweat à capuche"], ["Chapeau", "Casquette"],
  ["Chapeau", "Casque"], ["Chaussettes", "Bas"], ["Chaussures", "Bottes"],
  ["Baskets", "Sandales"], ["Cravate", "Nœud papillon"],
  ["Ceinture", "Corde"], ["Écharpe", "Châle"], ["Lunettes", "Masque"],
  ["Costume", "Smoking"], ["Pyjama", "Peignoir"], ["Bikini", "Maillot"],

  // Nature
  ["Pluie", "Cascade"], ["Tempête", "Ouragan"], ["Soleil", "Feu"],
  ["Nuage", "Brouillard"], ["Vent", "Brise"], ["Tonnerre", "Éclair"],
  ["Arc-en-ciel", "Aurore"], ["Arbre", "Buisson"], ["Fleur", "Plante"],
  ["Rose", "Tulipe"], ["Herbe", "Mousse"], ["Cactus", "Bambou"],
  ["Champignon", "Truffe"],

  // Culture pop
  ["Super-héros", "Méchants"], ["Vampire", "Loup-garou"], ["Zombie", "Fantôme"],
  ["Magicien", "Sorcière"], ["Dragon", "Phénix"], ["Chevalier", "Samouraï"],
  ["Pirate", "Marin"], ["Cowboy", "Hors-la-loi"], ["Ninja", "Assassin"],
  ["Cowboy", "Chevalier"], ["Ninja", "Samouraï"],
  ["Robot", "Androïde"], ["Alien", "Monstre"], ["Roi", "Empereur"],
  ["Reine", "Princesse"], ["Prince", "Duc"],

  // Outils
  ["Marteau", "Perceuse"], ["Tournevis", "Clé"], ["Scie", "Couteau"],
  ["Perceuse", "Marteau-piqueur"], ["Clou", "Colle"], ["Corde", "Ficelle"],
  ["Échelle", "Escalier"], ["Seau", "Baril"], ["Boîte", "Caisse"],
  ["Sac", "Sac à dos"], ["Valise", "Mallette"], ["Portefeuille", "Sac à main"],
  ["Parapluie", "Parasol"], ["Clé", "Serrure"], ["Carte", "Boussole"],
  ["Télescope", "Microscope"], ["Lampe torche", "Lanterne"], ["Épée", "Bouclier"],
  ["Arc", "Arbalète"], ["Pistolet", "Fusil"], ["Bombe", "Grenade"],
  ["Pistolet", "Arc"], ["Bouclier", "Armure"],

  // Divertissement
  ["Échecs", "Dames"], ["Cartes", "Dés"], ["Puzzle", "Mots croisés"],
  ["Jeu vidéo", "Jeu de société"], ["Grand huit", "Grande roue"],
  ["Cirque", "Fête foraine"], ["Concert", "Festival"], ["Film", "Série"],
  ["Comédie", "Drame"], ["Horreur", "Thriller"],

  // École
  ["Sac à dos", "Sacoche"], ["Cahier", "Journal"], ["Calculatrice", "Abaque"],
  ["Gomme", "Effaceur"], ["Agrafeuse", "Scotch"], ["Feutre", "Surligneur"],
  ["Dossier", "Classeur"], ["Tableau blanc", "Tableau noir"],

  // Argent
  ["Espèces", "Or"], ["Pièce", "Billet"], ["Or", "Soleil"],
  ["Diamant", "Rubis"], ["Trésor", "Butin"], ["Banque", "Coffre-fort"],
  ["Action", "Obligation"],

  // Abstrait
  ["Amour", "Amitié"], ["Colère", "Frustration"], ["Joie", "Bonheur"],
  ["Peur", "Anxiété"], ["Rêve", "Cauchemar"], ["Espoir", "Vœu"],
  ["Vérité", "Fait"], ["Mensonge", "Secret"],

  // Temps
  ["Printemps", "Automne"], ["Été", "Hiver"], ["Matin", "Aube"],
  ["Jour", "Semaine"], ["Noël", "Nouvel An"], ["Halloween", "Pâques"],
  ["Anniversaire", "Jubilé"], ["Mariage", "Enterrement"],

  // Divers
  ["Gym", "Spa"], ["Piscine", "Jacuzzi"], ["Sauna", "Hammam"],
  ["Tente", "Cabane"], ["Feu de joie", "Cheminée"], ["BBQ", "Pique-nique"],
  ["Vacances", "Congés"], ["Road trip", "Croisière"], ["Rando", "Camping"],
  ["Pêche", "Chasse"], ["Peinture", "Dessin"], ["Photo", "Vidéo"],
  ["Lecture", "Écriture"], ["Sommeil", "Sieste"], ["Course", "Jogging"],
  ["Marche", "Défilé"], ["Pleurs", "Rires"], ["Chuchotement", "Cri"],
  ["Câlin", "Baiser"], ["Poignée de main", "Check"],

  // Tech
  ["Internet", "Wi-Fi"], ["Email", "SMS"], ["Site web", "Appli"],
  ["Email", "Lettre"], ["Bluetooth", "USB"], ["Batterie", "Prise"], ["Chargeur", "Câble"],
  ["Enceinte", "Casque"], ["Clavier", "Souris"], ["Imprimante", "Scanner"],
  ["Portefeuille", "Compte"],

  // Mythes
  ["Licorne", "Pégase"], ["Sirène", "Néréide"], ["Fée", "Elfe"],
  ["Gobelin", "Orc"], ["Fantôme", "Zombie"], ["Ange", "Démon"],
  ["Dieu", "Diable"],

  // Aléatoire
  ["Savon", "Shampoing"], ["Brosse à dents", "Dentifrice"],
  ["Rasoir", "Peigne"], ["Parfum", "Eau de Cologne"], ["Rouge à lèvres", "Mascara"],
  ["Collier", "Bracelet"], ["Bague", "Boucle d'oreille"], ["Couronne", "Diadème"],
  ["Lunettes", "Lentilles"], ["Pansement", "Plâtre"], ["Pilule", "Vitamine"],
  ["Bonbon", "Gâteau"], ["Guimauve", "Nuage"],
  ["Popcorn", "Chips"], ["Noix", "Graine"], ["Miel", "Sirop d'érable"],
  ["Sel", "Sable"], ["Poivre", "Cannelle"], ["Beurre", "Margarine"],
  ["Yaourt", "Flan"], ["Fromage", "Beurre"], ["Œuf", "Tofu"],
  ["Riz", "Quinoa"], ["Blé", "Avoine"],

  // Avancé
  ["Brise", "Souffle"],
  ["Ombre", "Reflet"],
  ["Silence", "Vide"],
  ["Pont", "Tunnel"],
  ["Passeport", "Ticket"],
  ["Batterie", "Carburant"],
  ["Signature", "Empreinte"],
  ["Volcan", "Geyser"],
  ["Statue", "Mannequin"],
  ["Boussole", "Ancre"],
  ["Miroir", "Fenêtre"],
  ["Berceau", "Cercueil"],
  ["Masque", "Maquillage"],
  ["Poison", "Médicament"],
];

// Optional flavor text shown to civilians/undercover/The Ghost
const ROLE_FLAVOR = {
  en: {
    civilian: [
      "Stay subtle. Stay calm.",
      "Hide in the herd.",
      "Don't be the giveaway.",
      "Speak softly. Listen harder.",
      "Trust no one too quickly.",
    ],
    undercover: [
      "You don't have the same word. Bluff well.",
      "Listen first. Speak last if you can.",
      "A vague word is a safe word.",
      "Echo. Mimic. Survive.",
      "The herd is watching.",
    ],
    ghost: [
      "You have no word. Improvise.",
      "Listen carefully. Steal a clue.",
      "If caught, one guess saves you.",
      "Bluff. Borrow. Survive.",
      "The shadows are your costume.",
    ]
  },
  fr: {
    civilian: [
      "Restez subtil. Restez calme.",
      "Fondez-vous dans la masse.",
      "Ne soyez pas trop évident.",
      "Parlez peu. Écoutez beaucoup.",
      "Ne faites pas confiance trop vite.",
    ],
    undercover: [
      "Vous n'avez pas le même mot. Bluffez.",
      "Écoutez d'abord. Parlez en dernier.",
      "Un mot vague est un mot sûr.",
      "Imitez. Survivez.",
      "Le troupeau vous observe.",
    ],
    ghost: [
      "Vous n'avez pas de mot. Improvisez.",
      "Écoutez bien. Volez un indice.",
      "Si démasqué, devinez le mot.",
      "Bluffez. Empruntez. Survivez.",
      "L'ombre est votre costume.",
    ]
  }
};

function pickRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function pickWordPair(lang = 'en') {
  const list = lang === 'fr' ? WORD_PAIRS_FR : WORD_PAIRS_EN;
  const pair = pickRandom(list);
  // Randomly assign which word is civilian vs undercover so it's unpredictable
  if (Math.random() < 0.5) return { civilian: pair[0], undercover: pair[1] };
  return { civilian: pair[1], undercover: pair[0] };
}
